"""init

Revision ID: 0001
Revises: 
Create Date: 2023-05-16 16:55:45.384884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AptosPolygonBridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addressAptos', sa.String(), nullable=False),
    sa.Column('privateKeyAptos', sa.String(), nullable=True),
    sa.Column('addressPolygon', sa.String(), nullable=False),
    sa.Column('privateKeyPolygon', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('aptos_txn', sa.String(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_AptosPolygonBridge_addressAptos'), 'AptosPolygonBridge', ['addressAptos'], unique=False)
    op.create_index(op.f('ix_AptosPolygonBridge_addressPolygon'), 'AptosPolygonBridge', ['addressPolygon'], unique=False)
    op.create_table('PolygonAptosBridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addressPolygon', sa.String(), nullable=False),
    sa.Column('privateKeyPolygon', sa.String(), nullable=True),
    sa.Column('addressAptos', sa.String(), nullable=False),
    sa.Column('privateKeyAptos', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('claimed', sa.Boolean(), nullable=False),
    sa.Column('polygon_txn', sa.String(), nullable=True),
    sa.Column('creationDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PolygonAptosBridge_addressAptos'), 'PolygonAptosBridge', ['addressAptos'], unique=False)
    op.create_index(op.f('ix_PolygonAptosBridge_addressPolygon'), 'PolygonAptosBridge', ['addressPolygon'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PolygonAptosBridge_addressPolygon'), table_name='PolygonAptosBridge')
    op.drop_index(op.f('ix_PolygonAptosBridge_addressAptos'), table_name='PolygonAptosBridge')
    op.drop_table('PolygonAptosBridge')
    op.drop_index(op.f('ix_AptosPolygonBridge_addressPolygon'), table_name='AptosPolygonBridge')
    op.drop_index(op.f('ix_AptosPolygonBridge_addressAptos'), table_name='AptosPolygonBridge')
    op.drop_table('AptosPolygonBridge')
    # ### end Alembic commands ###
