"""combine

Revision ID: 0001
Revises: 
Create Date: 2023-10-23 14:24:46.974776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ScrollCombine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('srcCurrency', sa.String(), nullable=True),
    sa.Column('dstCurrency', sa.String(), nullable=True),
    sa.Column('srcAmount', sa.Float(), nullable=True),
    sa.Column('dstAmount', sa.Float(), nullable=True),
    sa.Column('txnHash', sa.String(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('approvedFor', sa.String(), nullable=True),
    sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ScrollCombine_address'), 'ScrollCombine', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ScrollCombine_address'), table_name='ScrollCombine')
    op.drop_table('ScrollCombine')
    # ### end Alembic commands ###
