"""bitcoinbridgeswap

Revision ID: 0002
Revises: 0001
Create Date: 2023-05-25 14:09:29.257326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BitcoinBridgeSwap',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(), nullable=False),
        sa.Column('privateKey', sa.String(), nullable=True),
        sa.Column('src', sa.String(), nullable=True),
        sa.Column('dst', sa.String(), nullable=True),
        sa.Column('amount', sa.Float(), nullable=True),
        sa.Column('creationDate', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BitcoinBridgeSwap_address'), 'BitcoinBridgeSwap', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BitcoinBridgeSwap_address'), table_name='BitcoinBridgeSwap')
    op.drop_table('BitcoinBridgeSwap')
    # ### end Alembic commands ###
