"""rhino_bridge

Revision ID: 0002
Revises: 0001
Create Date: 2023-11-01 18:03:47.095968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RhinoBridge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('srcCurrency', sa.String(), nullable=True),
    sa.Column('dstCurrency', sa.String(), nullable=True),
    sa.Column('srcAmount', sa.Float(), nullable=True),
    sa.Column('dstAmount', sa.Float(), nullable=True),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_RhinoBridge_address'), 'RhinoBridge', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_RhinoBridge_address'), table_name='RhinoBridge')
    op.drop_table('RhinoBridge')
    # ### end Alembic commands ###
